version: '3'

services:
  jenkins:
      image: <your registry here>/jenkins:latest
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      ports:
          - '8080:8080'
          - '50000:50000'
      environment:
         JAVA_OPTS: "-Djava.awt.headless=true -Dmail.smtp.starttls.enable=true"
      volumes:
          - jenkins-data:/var/jenkins_home/
          - /var/run/docker.sock:/var/run/docker.sock
          - <HOST_PATH_SSH>/.ssh:/home/jenkins/.ssh
  portainer:
      image: portainer/portainer
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      ports:
          - '9000:9000'
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
volumes:
    portainer-data:
    jenkins-data: